server:
  port: 8889

spring:
  application:
    name: configservice
  cloud:
    config:
      server:
        git:
          uri: file:///home/darek/Devel/Workspace/Spring/spring-io-lab7-config

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
